# WINDOWS CONFIGURATION
WIN_W, WIN_H = 900, 600
WIN_T = "Quiz Application"


# COLOR CONFIGURATION
BLACK = "#000000"
P_COL = "#0D1A1C"
S_COL = "#2E3532"
T_COL = "#7E9181"
TXT_COL = "#FFFFFF"


# PATH CONFIGURATIONS
PRI_IMG = "deps/quizImg.png"
GRADE_IMG = "deps/grade.png"

# FONT CONFIGURATION
FONT_FAM = "Arial"
GRADE_FONT = 54
FONT_SIZE_HEADING = 32
FONT_SIZE = 17
SM_FONT_SIZE = 15
VSM_FONT_SIZE = 12


# MYSQL CONFIGURATION
HOST = "127.0.0.1"
USER = "root"
PWD = "Quiz@mysql1234"
DB = "quiz_project"
AUTH_TABLE, RESULT_TABLE, QUIZ_TABLE = "auth", "result", "quiz"